on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  linked-issue-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check for linked issue
      id: check-issue
      run: |
        ISSUE_REGEX="(^|\s)#([0-9]+)($|\s)"
        echo "Pull request body: ${{ github.event.pull_request.issue_url }}"
        if [[ ! ${{ github.event.pull_request.body }} =~ $ISSUE_REGEX ]]; then
          echo "No issue linked in the pull request description."
          echo "::error::No issue linked in the pull request description."
          exit   1
        fi

    - name: Set status check
      if: steps.check-issue.outcome == 'failure'
      run: |
        echo "Setting status check to failure."
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          -d '{"state":"failure","context":"Linked Issue Check","description":"No issue linked in the pull request description."}'
